name: q_lock
description: "A new Flutter project."

publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.3.3
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.5
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_contacts: ^1.1.9+2
  flutter_image_compress: ^2.4.0
  flutter_intl_phone_field: ^0.0.4
  flutter_local_notifications: ^19.0.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  permission_handler: ^11.3.0
  pointycastle: ^4.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"
  min_sdk_android: 21
  
  # Add these lines for Android adaptive icons
  adaptive_icon_background: "#725BA4" # or any other hex color you want
  adaptive_icon_foreground: "assets/images/launch_icon.png"
  
  web:
    generate: true
    image_path: "assets/images/launch_icon.png"
    background_color: "#725BA4"
    theme_color: "#725BA4"
    
  windows:
    generate: true
    image_path: "assets/images/launch_icon.png"
    icon_size: 48
    
  macos:
    generate: true
    image_path: "assets/images/launch_icon.png"